### ISSUE TITLE
Where are the card pics?

### ISSUE THREAD

**Issue by purerosefallen** [Hello23-Ygopro/ygopro-pm#10]
Are they undone or missing?
Or they could be downloaded somewhere else?
With pics, I could deliver this game to my friends!

**Comment by Hello23-Ygopro** [comment]
Please check your email.

I don't put cards pics on Github because if a person wants to download the repos the zip is too big and i update a lot. And i haven't decided the IDs for a lot of OCG-only and promo cards yet.
For now this mode is a "no-pics" version, i might upload it later or make a repos just for card pics only.

**Comment by Hello23-Ygopro** [comment]
https://github.com/Hello23-Ygopro/ygopro-pm/commit/5799d143a612b81adde2498311b73c4b6a498381
